<a href="https://colab.research.google.com/github/Phongcnttta01/Fruit_Classification/blob/main/Xulytiendulieu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Các thư viện

In [701]:
from collections import Counter
import numpy as np
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score

Tải dữ liệu lên

In [702]:
data = pd.read_csv('data.csv')

Kiểm tra dữ liệu

In [703]:
print(pd.isnull(data).sum())

fruit_name       0
fruit_subtype    0
mass             0
width            0
height           0
color_score      0
fruit_label      0
dtype: int64


In [704]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fruit_name     59 non-null     object 
 1   fruit_subtype  59 non-null     object 
 2   mass           59 non-null     int64  
 3   width          59 non-null     float64
 4   height         59 non-null     float64
 5   color_score    59 non-null     float64
 6   fruit_label    59 non-null     int64  
dtypes: float64(3), int64(2), object(2)
memory usage: 3.4+ KB
None


Cắt dữ liệu


In [705]:
X = data.iloc[:,2:6]
Y = data.iloc[:,0:1]
X = np.array(X)
Y = np.array(Y)
print(X)

[[192.     8.4    7.3    0.55]
 [180.     8.     6.8    0.59]
 [176.     7.4    7.2    0.6 ]
 [ 86.     6.2    4.7    0.8 ]
 [ 84.     6.     4.6    0.79]
 [ 80.     5.8    4.3    0.77]
 [ 80.     5.9    4.3    0.81]
 [ 76.     5.8    4.     0.81]
 [178.     7.1    7.8    0.92]
 [172.     7.4    7.     0.89]
 [166.     6.9    7.3    0.93]
 [172.     7.1    7.6    0.92]
 [154.     7.     7.1    0.88]
 [164.     7.3    7.7    0.7 ]
 [152.     7.6    7.3    0.69]
 [156.     7.7    7.1    0.69]
 [156.     7.6    7.5    0.67]
 [168.     7.5    7.6    0.73]
 [162.     7.5    7.1    0.83]
 [162.     7.4    7.2    0.85]
 [160.     7.5    7.5    0.86]
 [156.     7.4    7.4    0.84]
 [140.     7.3    7.1    0.87]
 [170.     7.6    7.9    0.88]
 [342.     9.     9.4    0.75]
 [356.     9.2    9.2    0.75]
 [362.     9.6    9.2    0.74]
 [204.     7.5    9.2    0.77]
 [140.     6.7    7.1    0.72]
 [160.     7.     7.4    0.81]
 [158.     7.1    7.5    0.79]
 [210.     7.8    8.     0.82]
 [164.  

Chuyển đổi dữ liệu

In [706]:
chuyendoi = preprocessing.LabelEncoder()
chuyendoi.fit(Y)
Y_chuyenDoi = chuyendoi.transform(Y)
print(Y_chuyenDoi)


[0 0 0 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:93: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/preprocessing/_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


Chuẩn hóa dữ liệu (min,max) (dữ liệu to)

In [707]:
Chuanhoa = preprocessing.MinMaxScaler(feature_range=(0,1))
X_Chuanhoa = Chuanhoa.fit_transform(X)

In [708]:
print(X_Chuanhoa)

[[0.40559441 0.68421053 0.50769231 0.        ]
 [0.36363636 0.57894737 0.43076923 0.10526316]
 [0.34965035 0.42105263 0.49230769 0.13157895]
 [0.03496503 0.10526316 0.10769231 0.65789474]
 [0.02797203 0.05263158 0.09230769 0.63157895]
 [0.01398601 0.         0.04615385 0.57894737]
 [0.01398601 0.02631579 0.04615385 0.68421053]
 [0.         0.         0.         0.68421053]
 [0.35664336 0.34210526 0.58461538 0.97368421]
 [0.33566434 0.42105263 0.46153846 0.89473684]
 [0.31468531 0.28947368 0.50769231 1.        ]
 [0.33566434 0.34210526 0.55384615 0.97368421]
 [0.27272727 0.31578947 0.47692308 0.86842105]
 [0.30769231 0.39473684 0.56923077 0.39473684]
 [0.26573427 0.47368421 0.50769231 0.36842105]
 [0.27972028 0.5        0.47692308 0.36842105]
 [0.27972028 0.47368421 0.53846154 0.31578947]
 [0.32167832 0.44736842 0.55384615 0.47368421]
 [0.3006993  0.44736842 0.47692308 0.73684211]
 [0.3006993  0.42105263 0.49230769 0.78947368]
 [0.29370629 0.44736842 0.53846154 0.81578947]
 [0.27972028 

Chuẩn hóa Standard(số âm)

Chia dữ liệu

In [709]:
X_train,  X_test, y_train, y_test = train_test_split(X_Chuanhoa, Y_chuyenDoi, test_size=0.2, random_state =60)

In [710]:
def fit(X, y):
  classes = np.unique(y)
  mean = {}
  variance = {}
  prior = {}

  for c in classes:
    X_c = X[y==c]
    mean[c] = X_c.mean(axis=0)
    variance[c] = X_c.var(axis=0)
    prior[c] = X_c.shape[0]/X.shape[0]

  return mean, variance, prior

In [711]:
def gaussian_probability(x, mean, variance):
  return (1/np.sqrt(2*np.pi*variance))*np.exp(-(x-mean)**2/(2*variance))

In [712]:
def predict(X, mean, variance, prior):
    predictions = []
    classes = list(mean.keys())

    for x in X:
        posteriors = []
        for c in classes:
            prior_log = np.log(prior[c])
            class_likelihood = np.sum(np.log(gaussian_probability(x, mean[c], variance[c])))
            posterior = prior_log + class_likelihood
            posteriors.append(posterior)

        predictions.append(classes[np.argmax(posteriors)])

    return np.array(predictions)

In [713]:
mean, variance, prior = fit(X_train, y_train)

In [714]:
predictions = predict(X_test, mean, variance, prior)
print()

In [715]:
cm = confusion_matrix(y_test, predictions)
print(cm)
accuracy_score(y_test, predictions)



[[1 0 0 0]
 [0 6 0 1]
 [0 0 1 0]
 [2 1 0 0]]


0.6666666666666666

In [716]:
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

In [717]:
def predict(X_train, y_train, X_test, k=3):
    predictions = []

    for x_test in X_test:
        distances = []

        for i, x_train in enumerate(X_train):
            distance = euclidean_distance(x_test, x_train)
            distances.append((distance, y_train[i]))

        distances.sort(key=lambda x: x[0])

        k_nearest_labels = [label for _, label in distances[:k]]

        most_common = Counter(k_nearest_labels).most_common(1)[0][0]
        predictions.append(most_common)

    return np.array(predictions)

In [718]:
predictions = predict(X_train, y_train, X_test, 3)



In [719]:
cm = confusion_matrix(y_test, predictions)
print(cm)
accuracy_score(y_test, predictions)

[[1 0 0 0]
 [0 7 0 0]
 [0 0 1 0]
 [0 0 0 3]]


1.0

# Mục mới